apiVersion: elbv2.aws.upbound.io/v1beta1
kind: LBTargetGroup
metadata:
  name: learn-crossplane-tg
  labels:
    component: alb
spec:
  forProvider:
    healthCheck:
      - healthyThreshold: 3
        interval: 30
        matcher: 200-399
        path: /healthz
        protocol: HTTP
        timeout: 5
        unhealthyThreshold: 3
    name: learn-crossplane-tg-ip
    port: 30080
    protocol: HTTP
    region: us-east-1
    targetType: ip
    vpcIdSelector:
      matchLabels:
        environment: dev
    tags:
      Name: learn-crossplane-tg
      Environment: dev
