apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: learn-crossplane-platform-role
  labels:
    component: iam
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: learn-crossplane-platform-role
      Environment: dev
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: learn-crossplane-platform-policy
  labels:
    component: iam
spec:
  forProvider:
    description: Platform access policy for applications and CI runners
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:PutObject",
              "s3:ListBucket",
              "ecr:GetAuthorizationToken",
              "ecr:BatchCheckLayerAvailability",
              "ecr:GetDownloadUrlForLayer",
              "ecr:BatchGetImage",
              "ecr:PutImage",
              "ecr:InitiateLayerUpload",
              "ecr:UploadLayerPart",
              "ecr:CompleteLayerUpload",
              "ecr:DescribeRepositories",
              "secretsmanager:GetSecretValue",
              "secretsmanager:DescribeSecret"
            ],
            "Resource": "*"
          }
        ]
      }
    tags:
      Name: learn-crossplane-platform-policy
      Environment: dev
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: learn-crossplane-platform-attach
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        component: iam
    roleSelector:
      matchLabels:
        component: iam
