apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: monorepo-ci-pipeline
  namespace: tekton-ci
spec:
  description: End-to-end CI pipeline for cloning repo, building 6 microservices to ECR, and updating GitOps manifests.
  workspaces:
    - name: shared-data
  params:
    - name: repoUrl
      type: string
      default: "https://github.com/Hoangvu75/localstack-crossplane-devops-platform.git"
    - name: gitRevision
      type: string
      default: "main"
    - name: registryHost
      type: string
      default: "000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566"
    - name: projectName
      type: string
      default: "learn-crossplane"
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repoUrl)
        - name: revision
          value: $(params.gitRevision)

    - name: build-and-push-images
      taskRef:
        name: monorepo-build-and-push
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: registryHost
          value: $(params.registryHost)
        - name: projectName
          value: $(params.projectName)

    - name: update-gitops-manifests
      taskRef:
        name: git-update-workloads
      runAfter:
        - build-and-push-images
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: registryHost
          value: $(params.registryHost)
        - name: projectName
          value: $(params.projectName)
