#!/usr/bin/env bash
# Where everything is, whether it answers, and what to log in with.
#
# Read top to bottom. The first section that looks wrong is the one to fix, because
# everything below it depends on that one.
#
# ── Why this is a script and not a make target ──────────────────────────────
# It was folded into `make status` when scripts/ went from nine files to four. That was
# the wrong call for this machine: `make` is not installed, so the target was unreachable.
# A read-only diagnostic is also not the thing the GitOps argument was about -- it changes
# no state and owns no desired state. The four lifecycle scripts are still the whole
# imperative surface.
#
# Every address below is READ from the AWS API rather than written down. LocalStack
# assigns the ALB DNS names and the CloudFront distribution id at creation time, and they
# change whenever the emulated resources are recreated.
. "$(dirname "$0")/lib.sh"

require_tool kubectl aws curl

hr() { printf '%s\n' "------------------------------------------------------------------------"; }

# LocalStack binds nothing on port 80. Every emulated endpoint is multiplexed behind the
# gateway port and routed by Host header, so :4566 is part of the URL, not a detail.
GW=4566

probe() {
  # $1 = url. Prints the HTTP status, or a dash when nothing answered at all.
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 25 "$1" 2>/dev/null)
  if [ -z "$code" ] || [ "$code" = "000" ]; then echo "no answer"; else echo "$code"; fi
}

alb_dns() {
  # $1 = load balancer name.
  aws_ elbv2 describe-load-balancers --names "$1" \
    --query 'LoadBalancers[0].DNSName' --output text 2>/dev/null || echo ""
}

echo ""
hr
echo " ENDPOINTS"
hr

APP_DNS=$(alb_dns "${PROJECT_NAME}-alb")
ARGO_DNS=$(alb_dns "${PROJECT_NAME}-argocd-alb")
SIGNOZ_DNS=$(alb_dns "${PROJECT_NAME}-signoz-alb")
JENKINS_DNS=$(alb_dns "${PROJECT_NAME}-jenkins-alb")
CF_DOMAIN=$(aws_ cloudfront list-distributions \
  --query 'DistributionList.Items[0].DomainName' --output text 2>/dev/null || echo "")

# Three fields: label, host, and the path to probe.
#
# Jenkins is the reason for the third. It answers / with 403 because anonymous read is
# off in casc/jenkins.yaml, so probing / would print a number that looks like a failure
# every single time and train you to ignore it. /login returns 200 to an unauthenticated
# request and is served by the same web tier -- which is also why the ALB target group
# health-checks that path rather than /.
for ROW in "Web app|${APP_DNS}|/" \
           "ArgoCD|${ARGO_DNS}|/" \
           "Jenkins|${JENKINS_DNS}|/login" \
           "SigNoz|${SIGNOZ_DNS}|/" \
           "CloudFront|${CF_DOMAIN}|/"; do
  NAME="${ROW%%|*}"
  REST="${ROW#*|}"
  HOST="${REST%%|*}"
  PATH_="${REST##*|}"
  if [ -z "$HOST" ] || [ "$HOST" = "None" ]; then
    printf "  %-11s %-62s %s\n" "$NAME" "(not created yet)" "-"
    continue
  fi
  URL="http://${HOST}:${GW}${PATH_}"
  printf "  %-11s %-62s %s\n" "$NAME" "$URL" "$(probe "$URL")"
done


echo ""
hr
echo " CREDENTIALS"
hr

ARGO_PW=$(kubectl -n argocd get secret argocd-initial-admin-secret \
  -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null || echo "")
if [ -n "$ARGO_PW" ]; then
  printf "  %-11s %s / %s\n" "ArgoCD" "admin" "$ARGO_PW"
else
  echo "  ArgoCD      secret argocd-initial-admin-secret not found."
  echo "              ArgoCD deletes it once the password is changed, which is normal --"
  echo "              use the password you set. To reset it, delete the argocd-secret key:"
  echo "                kubectl -n argocd patch secret argocd-secret -p '{\"data\":{\"admin.password\":null,\"admin.passwordMtime\":null}}'"
  echo "                kubectl -n argocd rollout restart deployment/argocd-server"
fi

# SigNoz generates no password. It is not an omission here: on first visit it asks you to
# create an account, and that account lives in its own database. The only Secret in the
# signoz namespace is signoz-clickhouse-operator, which is internal ClickHouse plumbing
# and not a UI credential.
printf "  %-11s %s\n" "SigNoz" "no generated password -- first visit asks you to create an account"
printf "  %-11s %s\n" "Web app" "no authentication"
# Jenkins, unlike the Tekton Dashboard it replaced, actually has a login. The password is
# generated by bootstrap.sh and never rotated on re-run, so this is the one place it can
# be recovered from.
JENKINS_PW=$(kubectl -n jenkins get secret jenkins-secrets \
  -o jsonpath='{.data.adminPassword}' 2>/dev/null | base64 -d 2>/dev/null || echo "")
if [ -n "$JENKINS_PW" ]; then
  printf "  %-11s %s / %s\n" "Jenkins" "admin" "$JENKINS_PW"
else
  echo "  Jenkins     secret jenkins-secrets not found in namespace jenkins."
  echo "              It is created by scripts/bootstrap.sh and deliberately NOT rotated"
  echo "              on re-run, so a routine re-bootstrap cannot lock you out."
  echo "              Recreate it with:  make bootstrap"
fi

echo ""
hr
echo " ALB TARGET HEALTH"
hr
# A stale target is invisible except as a 503 from the ALB. The node gets a new container
# IP whenever k3d recreates the cluster, which is why the localstack-wiring CronJob
# re-registers these every two minutes.
for PAIR in "${PROJECT_NAME}-tg-ip:30080:web app via ingress-nginx" \
            "${PROJECT_NAME}-argocd-tg:30081:argocd-server-nodeport" \
            "${PROJECT_NAME}-jenkins-tg:30082:jenkins-nodeport" \
            "${PROJECT_NAME}-signoz-tg:30083:signoz-nodeport"; do
  TG="${PAIR%%:*}"
  REST="${PAIR#*:}"
  PORT="${REST%%:*}"
  DESC="${REST#*:}"
  ARN=$(aws_ elbv2 describe-target-groups --names "$TG" \
    --query 'TargetGroups[0].TargetGroupArn' --output text 2>/dev/null || echo "")
  if [ -z "$ARN" ] || [ "$ARN" = "None" ]; then
    printf "  %-30s %-8s %s\n" "$TG" "-" "not created yet"
    continue
  fi
  STATE=$(aws_ elbv2 describe-target-health --target-group-arn "$ARN" \
    --query 'TargetHealthDescriptions[].[Target.Id,TargetHealth.State]' --output text 2>/dev/null \
    | tr '\t' ':' | tr '\n' ' ')
  printf "  %-30s :%-7s %s  (%s)\n" "$TG" "$PORT" "${STATE:-no targets registered}" "$DESC"
done

echo ""
hr
echo " WORKLOADS   (ErrImagePull here is EXPECTED until the first CI run finishes)"
hr
kubectl -n devops-apps get pods --no-headers 2>/dev/null \
  | awk '{printf "  %-34s %-10s %-22s restarts=%s\n",$1,$2,$3,$4}' \
  || echo "  namespace devops-apps not present yet"

# ArgoCD deploys the tag written in gitops/workloads/*/kustomization.yaml. Until the
# pipeline has built, pushed and committed a new tag, that tag names an image that does not
# exist, and the web app answers 503 with nothing actually broken.
echo ""
echo "  ECR repositories and whether anything has been pushed:"
for R in $(aws_ ecr describe-repositories --query 'repositories[].repositoryName' --output text 2>/dev/null | tr '\t' '\n'); do
  N=$(aws_ ecr list-images --repository-name "$R" --query 'length(imageIds)' --output text 2>/dev/null || echo "?")
  TAGS=$(aws_ ecr list-images --repository-name "$R" --query 'imageIds[].imageTag' --output text 2>/dev/null | tr '\t' ',' )
  printf "    %-38s images=%-4s %s\n" "$R" "$N" "${TAGS:-}"
done

echo ""
hr
echo " TEKTON CI"
hr
if kubectl get ns tekton-ci >/dev/null 2>&1; then
  if kubectl -n tekton-ci get secret git-credentials >/dev/null 2>&1; then
    echo "  git-credentials secret: present"
  else
    echo "  git-credentials secret: MISSING -- the git push step will fail."
    echo "                          Run: bash scripts/secrets.sh && bash scripts/bootstrap.sh"
  fi
  echo ""
  kubectl -n tekton-ci get pipelinerun --no-headers 2>/dev/null \
    | awk '{printf "  %-40s %-9s %-20s %s\n",$1,$2,$3,$4}' \
    || echo "  no PipelineRuns yet"
  kubectl -n tekton-ci get taskrun --no-headers 2>/dev/null \
    | awk '{printf "    %-46s %-9s %s\n",$1,$2,$3}'

  # The build step prints one line per service. Showing the tail inline answers "is it
  # stuck or just slow" without having to find the pod name first.
  BPOD=$(kubectl -n tekton-ci get pods --no-headers 2>/dev/null \
    | grep "build-and-push" | grep -v Completed | head -1 | awk '{print $1}')
  if [ -n "$BPOD" ]; then
    DONE=$(kubectl -n tekton-ci logs "$BPOD" --all-containers --tail=2000 2>/dev/null | grep -c '^>>> OK: ' || true)
    echo ""
    echo "  build progress: ${DONE:-0}/6 images published"
    kubectl -n tekton-ci logs "$BPOD" --all-containers --tail=400 2>/dev/null \
      | grep -E '^>>> (Building|Pushing|OK)|^!!!|Docker daemon ready' | tail -4 | sed 's/^/    /'
    echo ""
    echo "  follow it live:"
    echo "    kubectl -n tekton-ci logs -f ${BPOD} --all-containers"
  fi
else
  echo "  namespace tekton-ci not present yet -- ArgoCD has not synced platform-tekton"
fi

echo ""
hr
echo " HOW TO WATCH A BUILD"
hr
cat <<'HELP'
  Status, refreshed as it changes:
    kubectl -n tekton-ci get pipelinerun -w

  Live log of the build step (the slow one -- six images, no layer cache, inside DinD):
    POD=$(kubectl -n tekton-ci get pods --no-headers | grep build-and-push | head -1 | awk '{print $1}')
    kubectl -n tekton-ci logs -f "$POD" --all-containers

  Per-service progress only:
    kubectl -n tekton-ci logs "$POD" --all-containers | grep -E '^>>> (Building|OK)'

  Tekton Dashboard -- graphical pipeline view and per-step logs, the easiest way to watch
  a build. It has its OWN ALB (NodePort 30082), so no port-forward is needed. The URL is
  printed in the ENDPOINTS section above.

  It opens on whichever namespace you pick in the header. PipelineRuns live in tekton-ci,
  not tekton-pipelines -- the controllers are in tekton-pipelines and the runs were moved
  out because that namespace enforces PodSecurity restricted.

  port-forward still works if the ALB is not up yet, because the upstream Service was
  left untouched:
    kubectl -n tekton-pipelines port-forward svc/tekton-dashboard 9097:9097
    http://localhost:9097

  Why a TaskRun stopped:
    kubectl -n tekton-ci describe taskrun <name>

  Start a run by hand:
    kubectl create -f gitops/platform/tekton/ci/pipelinerun-manual.yaml

  Exercise the trigger path instead, interceptors included (README section 8.2):
    kubectl -n tekton-ci port-forward svc/el-ci-webhook-listener 8089:8080 &
    bash scripts/trigger-webhook.sh   # if present, otherwise the curl in README 8.2

  Remember that kubectl itself needs AWS credentials in the environment: the kubeconfig
  written by `aws eks update-kubeconfig` uses an exec plugin with env: null, so every call
  inherits the shell. This script gets them from .env via lib.sh; a bare terminal needs
    export AWS_ACCESS_KEY_ID=mock_access_key AWS_SECRET_ACCESS_KEY=mock_secret_key
    export AWS_DEFAULT_REGION=us-east-1
HELP
echo ""
