apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: learn-crossplane-private-a
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        environment: dev
    tags:
      Name: learn-crossplane-private-a
      Environment: dev
      kubernetes.io/role/internal-elb: "1"
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: learn-crossplane-private-b
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.0.2.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        environment: dev
    tags:
      Name: learn-crossplane-private-b
      Environment: dev
      kubernetes.io/role/internal-elb: "1"
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: learn-crossplane-public-a
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.0.3.0/24
    mapPublicIpOnLaunch: true
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        environment: dev
    tags:
      Name: learn-crossplane-public-a
      Environment: dev
      kubernetes.io/role/elb: "1"
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: learn-crossplane-public-b
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.0.4.0/24
    mapPublicIpOnLaunch: true
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        environment: dev
    tags:
      Name: learn-crossplane-public-b
      Environment: dev
      kubernetes.io/role/elb: "1"
